do not use system python3 for serving wasm files
ethanhs/python-wasm pull request #49
Opened 2022-01-18 16:04 UTC by pmp-p

The wasm mimetype is not present in < 3.9  so instantiate streaming could fail silently on chrome and firefox
The host build is expected to be the latest Python available so just use it instead of any older system one

2022-01-18 16:11 UTC, tiran commented
This should not be an issue. Python reads system-wide mimetypes registries like ``/etc/mime.types``.

```
$ grep wasm /etc/mime.types 
application/wasm                    wasm
```

2022-01-18 16:13 UTC, tiran requested changes
This breaks my workflow. I'm building build and host Python inside a container. The Linux distro inside the container has a different ABI than my host system.

2022-01-18 16:41 UTC, tiran commented
``application/wasm`` is available in Python 3.7+, https://github.com/python/cpython/commit/2a99fd911ebeecedbb250a05667cd46eca4735b9 Which distro system Python does not have the wasm mimetype?

2022-01-18 16:43 UTC, pmp-p commented
i've found at least a mandriva flavour without it and it has 3.6.5 as system python.
recent debian / fedora  were ok for /etc/mime.types

2022-01-18 16:52 UTC, tiran commented
3.6 + missing mime.types is a problem. Simplest solution is to do:

```
import mimetypes
mimetypes.add_type(".wasm", "application/wasm")
```

2022-01-18 17:19 UTC, pmp-p commented
it should work but it does not i find MyHTTPRequestHandler.extensions_map[".wasm"] empty on 3.6.5

2022-02-26 18:06 UTC, brettcannon requested changes

2022-02-26 18:06 UTC, brettcannon commented on browser-ui/server.py
> +if not ".wasm" in mimetypes.types_map:
```suggestion
if ".wasm" not in mimetypes.types_map:
```

2022-02-26 18:06 UTC, brettcannon commented on browser-ui/server.py
> +    mimetypes.types_map[".wasm"] = "application/wasm"
```suggestion
    mimetypes.add_type("application/wasm", ".wasm")
```

2022-03-03 02:05 UTC, ethanhs approved these changes

2022-03-03 19:49 UTC, brettcannon approved these changes

2022-03-04 18:46 UTC, merged